In [1]:
import pandas as pd
import seaborn as sns
import difflib
# !pip install geopy
from geopy import GoogleV3
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score

In [2]:
data = pd.read_csv("dt.csv")

In [3]:
X = data[['Вредоносность', 'Регистрация в реестре', 'Используется арендованное помещение', 'Категория объекта', 'Колличество жалоб на предприятие']]
y = data[['Маскируют свою деятельность']]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75)

In [5]:
max_depth_values = range(1, 40)
scores_data = pd.DataFrame()

In [6]:
for max_depth in max_depth_values:
    clf = tree.DecisionTreeClassifier(criterion="entropy", max_depth=max_depth)
    clf.fit(X_train, y_train)
    train_score = clf.score(X_train, y_train)
    test_score = clf.score(X_test, y_test)

    temp_score_data = pd.DataFrame({
        "max_depth": [max_depth],
        "train_score": [train_score],
        "test_score": [test_score]
    })

    scores_data = scores_data.append(temp_score_data)

In [7]:
scores_data

   max_depth  train_score  test_score
0          1     0.550926    0.575342
0          2     0.597222    0.589041
0          3     0.615741    0.630137
0          4     0.680556    0.630137
0          5     0.694444    0.602740
0          6     0.736111    0.643836
0          7     0.763889    0.589041
0          8     0.791667    0.575342
0          9     0.824074    0.506849
0         10     0.847222    0.547945
0         11     0.865741    0.534247
0         12     0.865741    0.520548
0         13     0.865741    0.520548
0         14     0.865741    0.520548
0         15     0.865741    0.520548
0         16     0.865741    0.520548
0         17     0.865741    0.534247
0         18     0.865741    0.534247
0         19     0.865741    0.534247
0         20     0.865741    0.534247
0         21     0.865741    0.534247
0         22     0.865741    0.520548
0         23     0.865741    0.534247
0         24     0.865741    0.520548
0         25     0.865741    0.520548
0         26     0.865741    0.534247
0         27     0.865741    0.534247
0         28     0.865741    0.534247
0         29     0.865741    0.520548
0         30     0.865741    0.520548
0         31     0.865741    0.520548
0         32     0.865741    0.520548
0         33     0.865741    0.534247
0         34     0.865741    0.534247
0         35     0.865741    0.534247
0         36     0.865741    0.520548
0         37     0.865741    0.520548
0         38     0.865741    0.534247
0         39     0.865741    0.534247

In [8]:
scores_data_long = pd.melt(scores_data, id_vars = ['max_depth'], value_vars = ['train_score','test_score'], var_name = 'set_type', value_name = 'score')

# sns.lineplot(x='max_depth', y='score', hue='set_type', data=scores_data_long)

In [9]:
parameters = {'max_depth': range(3, 400)}
clf = GridSearchCV(tree.DecisionTreeClassifier(), parameters, n_jobs = 4)
clf.fit(X_train, y_train)
tree_model = clf.best_estimator_
print (clf.best_score_, clf.best_params_)

0.6017970401691332 {'max_depth': 219}

In [12]:
scores_data_long.plot(x='max_depth', y='score')